### ISSUE TITLE
English content review

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/50-drops-of-php#1]
I am not a native English speaker :)
If you see some mistake or some misspelling in one of markdown doc, please, smile and submit a PR ;)

Markdown files are in the *content* directory, in *main* branch:
https://github.com/roberto-butti/50-drops-of-php/tree/main/content

It would be appreciated

**Comment by anushka9555** [comment]
Hii can I work on this issue?

**Comment by roberto-butti** [comment]
> Hii can I work on this issue?

Hi @anushka9555  , thank you for your availability. If you are interested in this, i would like to suggest you take a look about this : https://github.com/roberto-butti/some-drops-of-php  . Basically, we are executing the 50 drops of PHP adding more functions, and deliver the HTML format (more accessible)

**Comment by roberto-butti** [comment]
https://github.com/roberto-butti/some-drops-of-php/issues/15
