### ISSUE TITLE
PHP_EOL (string) The correct 'End Of Line' symbol for this platform.

### ISSUE THREAD

**Issue by dr41d45** [roberto-butti/50-drops-of-php#5]
Bad: `PHP_EOL()`
Correct: `PHP_EOL`

https://github.com/roberto-butti/50-drops-of-php/blob/60bd641696a5a69964b9566ba964fb110b835948/README.md?plain=1#L69

**Comment by roberto-butti** [comment]
Thank you @dr41d45  for the feedback!
