### ISSUE TITLE
Added links to Readme file

### ISSUE THREAD

**Issue by nokysin** [roberto-butti/50-drops-of-php#7]
At now the Readme file contains a lot of information (Table of Content) without related links. 
Links to relevant files should be added to simplify navigation through the repository.

I'm already prepared [needed PR](https://github.com/roberto-butti/50-drops-of-php/pull/8)

**Comment by roberto-butti** [comment]
Hi @nokysin thank you for your feedback, and your excellent Pull Request, very useful!

I already merged your PR #8  into the main branch.


Thank you!
